sudo apt-get install python3.7
 python3 --version
python3 --version
sudo apt-get update
sudo apt-get install python3-pip
pip install flask
sudo apt-get install python-dev default-libmysqlclient-dev libssl-dev
sudo python3 -m venv venv
sudo python -m venv venv
sudo python3 -m venv venv
 python3 get-pip.py --user
python3 get-pip.py --user
sudo python3 get-pip.py --user
sudo curl -O https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py --user
sudo python3 -m venv venv
sudo apt install python3.8-venv
sudo python3 -m venv venv
cp /usr/share/nano/python.nanorc $HOME/.nanorc
source venv/bin/activate
sudo mkdir pyflask && cd pyflask
sudo nano main.py
export FLASK_APP=main.py
flask run --host=0.0.0.0
sudo apt install flask
sudo pip  install flask
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
sudo nano main.py
flask run --host=0.0.0.0
sudo nano main.py
export FLASK_APP=main.py
flask run --host=0.0.0.0
sudo chmod -R ubuntu /home/ubuntu/

sudo chmod -R 775 /home/ubuntu/
export FLASK_APP=main.py
flask run --host=0.0.0.0
sudo pip install bs4
flask run --host=0.0.0.0
sudo pip install flask_mysqldb
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
screen
lsof -i tcp:5000
kill -9 80649
export FLASK_APP=main.py
kill -9 80649
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
screen
lsof -i tcp:5000
kill -9 84130
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
screen
lsof -i tcp:5000
kill -9 84964
export FLASK_APP=main.py
flask run --host=0.0.0.0
lsof -i tcp:5000
kill -9 86222
export FLASK_APP=main.py
flask run --host=0.0.0.0
screen
lsof -i tcp:5000
kill -9 87937
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
export FLASK_APP=main.py
flask run --host=0.0.0.0
screen
